on: [pull_request]

name: Automated tests workflow
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Cache
      - name: Restore Yarn from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      # ESLint
      - name: ESLint
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
